project_id = "inhzvcfoiovpotoxwwzf"

[functions.exobooster]
verify_jwt = false

[functions.exobooster-prices]
verify_jwt = false

[functions.campay-payment]
verify_jwt = false

[functions.alert-low-balance]
verify_jwt = false
